In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
from sklearn.linear_model import LogisticRegression

In [2]:
data = pd.read_excel("a1_Dataset_10Percent.xlsx")


In [3]:
data

ID  DemAffl  DemAge DemClusterGroup DemGender      DemReg  \
0      17147654      5.0     NaN             NaN       NaN         NaN   
1       8415498     15.0     NaN             NaN         M         NaN   
2      12107603      NaN     NaN             NaN         M    Midlands   
3      14400995      8.0    28.0             NaN         F         NaN   
4      28724674     14.0    67.0             NaN       NaN         NaN   
...         ...      ...     ...             ...       ...         ...   
22218  52830893     13.0    49.0               B         M  South East   
22219  52834058     13.0    65.0               B         F  South East   
22220  52834376     15.0    73.0               D         U  South East   
22221  52837057      9.0    70.0               B         F       North   
22222  52838096     11.0    66.0               B         F       North   

         DemTVReg LoyalClass  LoyalSpend  LoyalTime  TargetBuy  
0             NaN        Tin        0.01        5.0          0  
1             NaN       Gold     8000.00        5.0          1  
2            East        Tin        0.01        NaN          1  
3             NaN        Tin        0.01        NaN          1  
4             NaN        Tin        0.01        7.0          0  
...           ...        ...         ...        ...        ...  
22218      London     Silver      500.00        9.0          0  
22219      London     Silver     1500.00        5.0          0  
22220  S & S East       Gold     6053.06       12.0          0  
22221   Yorkshire       Gold     6000.00        5.0          0  
22222      N West     Silver     5000.00        5.0          0  

[22223 rows x 11 columns]

In [4]:
data.shape

(22223, 11)

# DATA PREPARATION

In [5]:
data= data.drop(['ID'],axis = 1)
data.head()

DemAffl  DemAge DemClusterGroup DemGender    DemReg DemTVReg LoyalClass  \
0      5.0     NaN             NaN       NaN       NaN      NaN        Tin   
1     15.0     NaN             NaN         M       NaN      NaN       Gold   
2      NaN     NaN             NaN         M  Midlands     East        Tin   
3      8.0    28.0             NaN         F       NaN      NaN        Tin   
4     14.0    67.0             NaN       NaN       NaN      NaN        Tin   

   LoyalSpend  LoyalTime  TargetBuy  
0        0.01        5.0          0  
1     8000.00        5.0          1  
2        0.01        NaN          1  
3        0.01        NaN          1  
4        0.01        7.0          0

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22223 entries, 0 to 22222
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   DemAffl          21138 non-null  float64
 1   DemAge           20715 non-null  float64
 2   DemClusterGroup  21549 non-null  object 
 3   DemGender        19711 non-null  object 
 4   DemReg           21758 non-null  object 
 5   DemTVReg         21758 non-null  object 
 6   LoyalClass       22223 non-null  object 
 7   LoyalSpend       22223 non-null  float64
 8   LoyalTime        21942 non-null  float64
 9   TargetBuy        22223 non-null  int64  
dtypes: float64(4), int64(1), object(5)
memory usage: 1.7+ MB


In [7]:
data.isna().sum()

DemAffl            1085
DemAge             1508
DemClusterGroup     674
DemGender          2512
DemReg              465
DemTVReg            465
LoyalClass            0
LoyalSpend            0
LoyalTime           281
TargetBuy             0
dtype: int64

In [8]:
data['DemAffl'] = data['DemAffl'].fillna(data['DemAffl'].mode()[0])
data['DemAge'] = data['DemAge'].fillna(data['DemAge'].mode()[0])
data['DemClusterGroup'] = data['DemClusterGroup'].fillna(data['DemClusterGroup'].mode()[0])
data['DemGender'] = data['DemGender'].fillna(data['DemGender'].mode()[0])
data['DemReg'] = data['DemReg'].fillna(data['DemReg'].mode()[0])
data['DemTVReg'] = data['DemTVReg'].fillna(data['DemTVReg'].mode()[0])
data['LoyalTime'] = data['LoyalTime'].fillna(data['LoyalTime'].mean())

In [9]:
data.isna().sum()

DemAffl            0
DemAge             0
DemClusterGroup    0
DemGender          0
DemReg             0
DemTVReg           0
LoyalClass         0
LoyalSpend         0
LoyalTime          0
TargetBuy          0
dtype: int64

In [10]:
data.head(20)

DemAffl  DemAge DemClusterGroup DemGender      DemReg    DemTVReg  \
0       5.0    51.0               C         F  South East      London   
1      15.0    51.0               C         M  South East      London   
2       8.0    51.0               C         M    Midlands        East   
3       8.0    28.0               C         F  South East      London   
4      14.0    67.0               C         F  South East      London   
5       8.0    65.0               C         F  South East      London   
6       7.0    41.0               C         F  South East      London   
7      13.0    50.0               C         F  South East      London   
8       8.0    36.0               C         F  South East      London   
9       8.0    51.0               C         M    Midlands      Ulster   
10      8.0    51.0               B         F  South East      London   
11      8.0    51.0               C         F    Midlands      Ulster   
12      8.0    51.0               C         U  South East  S & S East   
13     11.0    59.0               C         U  South East      London   
14     13.0    51.0               B         F  South East      London   
15      8.0    57.0               C         F       North   Yorkshire   
16      5.0    51.0               C         F    Midlands      Ulster   
17      8.0    54.0               C         F    Midlands      Ulster   
18      8.0    71.0               B         F  South East      London   
19      8.0    47.0               E         F  South East      London   

   LoyalClass  LoyalSpend  LoyalTime  TargetBuy  
0         Tin        0.01    5.00000          0  
1        Gold     8000.00    5.00000          1  
2         Tin        0.01    6.56467          1  
3         Tin        0.01    6.56467          1  
4         Tin        0.01    7.00000          0  
5      Silver     3000.00    3.00000          0  
6         Tin        0.01    7.00000          0  
7         Tin        0.01    5.00000          1  
8         Tin        0.01    9.00000          0  
9      Silver     2000.00    1.00000          0  
10       Gold     6000.00    1.00000          1  
11     Silver     5000.00   12.00000          1  
12       Gold    18633.51    3.00000          0  
13       Gold    12000.00    9.00000          0  
14       Gold     6000.00    2.00000          0  
15        Tin        0.01    5.00000          0  
16     Silver        0.02    5.00000          0  
17     Silver     5000.00    4.00000          0  
18       Gold     6000.00   26.00000          0  
19        Tin        0.01    8.00000          0

# CONVERTING CATEGORY TO NUMERIC

In [11]:
#labelEncoder
from sklearn.preprocessing import LabelEncoder

num = LabelEncoder()

data.DemClusterGroup = num.fit_transform(data.DemClusterGroup.astype('str'))
integer_mapping = {l: i for i, l in enumerate(num.classes_)}
print(integer_mapping)


data.DemGender = num.fit_transform(data.DemGender.astype('str'))
integer_mapping = {l: i for i, l in enumerate(num.classes_)}
print(integer_mapping)


data.DemReg = num.fit_transform(data.DemReg.astype('str'))
integer_mapping = {l: i for i, l in enumerate(num.classes_)}
print(integer_mapping)


data.DemTVReg = num.fit_transform(data.DemTVReg.astype('str'))
integer_mapping = {l: i for i, l in enumerate(num.classes_)}
print(integer_mapping)

data.LoyalClass = num.fit_transform(data.LoyalClass.astype('str'))
integer_mapping = {l: i for i, l in enumerate(num.classes_)}
print(integer_mapping)


{'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'U': 6}
{'F': 0, 'M': 1, 'U': 2}
{'Midlands': 0, 'North': 1, 'Scottish': 2, 'South East': 3, 'South West': 4}
{'Border': 0, 'C Scotland': 1, 'East': 2, 'London': 3, 'Midlands': 4, 'N East': 5, 'N Scot': 6, 'N West': 7, 'S & S East': 8, 'S West': 9, 'Ulster': 10, 'Wales & West': 11, 'Yorkshire': 12}
{'Gold': 0, 'Platinum': 1, 'Silver': 2, 'Tin': 3}


In [12]:
data.head(20)

DemAffl  DemAge  DemClusterGroup  DemGender  DemReg  DemTVReg  LoyalClass  \
0       5.0    51.0                2          0       3         3           3   
1      15.0    51.0                2          1       3         3           0   
2       8.0    51.0                2          1       0         2           3   
3       8.0    28.0                2          0       3         3           3   
4      14.0    67.0                2          0       3         3           3   
5       8.0    65.0                2          0       3         3           2   
6       7.0    41.0                2          0       3         3           3   
7      13.0    50.0                2          0       3         3           3   
8       8.0    36.0                2          0       3         3           3   
9       8.0    51.0                2          1       0        10           2   
10      8.0    51.0                1          0       3         3           0   
11      8.0    51.0                2          0       0        10           2   
12      8.0    51.0                2          2       3         8           0   
13     11.0    59.0                2          2       3         3           0   
14     13.0    51.0                1          0       3         3           0   
15      8.0    57.0                2          0       1        12           3   
16      5.0    51.0                2          0       0        10           2   
17      8.0    54.0                2          0       0        10           2   
18      8.0    71.0                1          0       3         3           0   
19      8.0    47.0                4          0       3         3           3   

    LoyalSpend  LoyalTime  TargetBuy  
0         0.01    5.00000          0  
1      8000.00    5.00000          1  
2         0.01    6.56467          1  
3         0.01    6.56467          1  
4         0.01    7.00000          0  
5      3000.00    3.00000          0  
6         0.01    7.00000          0  
7         0.01    5.00000          1  
8         0.01    9.00000          0  
9      2000.00    1.00000          0  
10     6000.00    1.00000          1  
11     5000.00   12.00000          1  
12    18633.51    3.00000          0  
13    12000.00    9.00000          0  
14     6000.00    2.00000          0  
15        0.01    5.00000          0  
16        0.02    5.00000          0  
17     5000.00    4.00000          0  
18     6000.00   26.00000          0  
19        0.01    8.00000          0

# CHECKING FOR MULTICOLLINEARITY

In [13]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

def cal_vif(z):
    vif = pd.DataFrame()
    vif['variables'] = z.columns
    vif['VIF'] = [variance_inflation_factor(z.values, i) for i in range(z.shape[1])]
    
    return vif



In [14]:
z = data.iloc[:,0:9]
cal_vif(z)

variables        VIF
0          DemAffl   6.278630
1           DemAge  10.734656
2  DemClusterGroup   3.659632
3        DemGender   1.435472
4           DemReg   2.474645
5         DemTVReg   3.752279
6       LoyalClass   3.851766
7       LoyalSpend   1.863196
8        LoyalTime   3.153032

# VARIABLE SELECTION

In [15]:
y = data.iloc[:, 9].values
x = data.iloc[:, 0:9].values

In [16]:
x

array([[5.00000000e+00, 5.10000000e+01, 2.00000000e+00, ...,
        3.00000000e+00, 1.00000000e-02, 5.00000000e+00],
       [1.50000000e+01, 5.10000000e+01, 2.00000000e+00, ...,
        0.00000000e+00, 8.00000000e+03, 5.00000000e+00],
       [8.00000000e+00, 5.10000000e+01, 2.00000000e+00, ...,
        3.00000000e+00, 1.00000000e-02, 6.56467049e+00],
       ...,
       [1.50000000e+01, 7.30000000e+01, 3.00000000e+00, ...,
        0.00000000e+00, 6.05306000e+03, 1.20000000e+01],
       [9.00000000e+00, 7.00000000e+01, 1.00000000e+00, ...,
        0.00000000e+00, 6.00000000e+03, 5.00000000e+00],
       [1.10000000e+01, 6.60000000e+01, 1.00000000e+00, ...,
        2.00000000e+00, 5.00000000e+03, 5.00000000e+00]])

In [17]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

# MODELLING

In [18]:
classifier = LogisticRegression(max_iter = 200)

classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)

C:\Anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [19]:
y_pred

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [20]:
import joblib
joblib.dump(classifier,'Classifier_LoyalCustomers')

['Classifier_LoyalCustomers']

In [21]:
print(confusion_matrix(y_test,y_pred))

[[3189  178]
 [ 689  389]]


In [22]:
print(accuracy_score(y_test,y_pred))

0.8049493813273341


In [23]:
predictions = classifier.predict_proba(x_test)
predictions

array([[0.86096288, 0.13903712],
       [0.64587799, 0.35412201],
       [0.49006239, 0.50993761],
       ...,
       [0.88737102, 0.11262898],
       [0.90441145, 0.09558855],
       [0.87298133, 0.12701867]])

In [24]:
#writing model output file
df_prediction_prob = pd.DataFrame(predictions,columns = ['prob_0','prob_1'])
df_test_data = pd.DataFrame(y_test,columns=['Actual Outcome'])
df_x_test = pd.DataFrame(x_test)

dfx = pd.concat([df_prediction_prob ,df_test_data, df_x_test], axis = 1)

In [25]:
dfx.head()

prob_0    prob_1  Actual Outcome     0     1    2    3    4    5    6  \
0  0.860963  0.139037               0  10.0  58.0  3.0  1.0  3.0  8.0  0.0   
1  0.645878  0.354122               0  10.0  51.0  2.0  0.0  3.0  8.0  0.0   
2  0.490062  0.509938               0  16.0  65.0  1.0  0.0  2.0  6.0  0.0   
3  0.914317  0.085683               0   5.0  60.0  3.0  0.0  3.0  3.0  2.0   
4  0.705173  0.294827               0   9.0  52.0  3.0  0.0  0.0  4.0  2.0   

          7    8  
0  12632.66  4.0  
1   6000.00  6.0  
2   6053.35  7.0  
3   5000.00  1.0  
4   3500.00  6.0